defaults:
  - gs: base
  - _self_ 

seed: 228

wandb:
  mode: "online" # "disabled" for no logging
  entity: "atopaloglu21"
  project: "Adv3DGS"
  group: null
  name: null
  tag: "debug"
    
train:
  gs_epochs: 0 # number of 3dgs iterations
  reduce_opacity: True 
  no_densify: False # if True, the model will not be densified
  max_lr: True 

load:
  gs: null #path to 3dgs checkpoint
  gs_step: null #number of iterations, e.g. 7000

device: "cuda:0"
verbose: true

init_wC:
  use: True # use EDGS (RoMA based)
  matches_per_ref: 15_000 # number of matches per reference
  num_refs: 180 # number of reference images
  nns_per_ref: 3 # number of nearest neighbors per reference
  scaling_factor: 0.001
  proj_err_tolerance: 0.01
  roma_model: "outdoors" # you can change this to "indoors" or "outdoors"
  add_SfM_init : False # If True, SfM points from COLMAP are kept alongside RoMA points

# New section for direct Point Cloud Initialization
init_direct_pcd:
  use: False  # Set to True to use this direct PCD initialization
  path: null  # Example: "path/to/your/dense_cloud.ply"
  spatial_lr_scale: 1.0 # Spatial LR scale for GaussianModel.create_from_pcd
